baseURL = "https://histologylab.ctl.columbia.edu/"
languageCode = "en-us"
title = "Histology Lab Manual"
theme = "ctl-histologylab"
googleAnalytics = "G-95YRSYPN9N"

[outputs]
  home = ["HTML","RSS", "JSON"]
